### ISSUE TITLE
"Hey Kevin, pick up some cheese" should return success/fail

### ISSUE THREAD

**Issue by kimjune01** [jyleong/voiceminder-server#10]
case success: say nothing.

case fail: say "Kevin's not available"

Dataflow:
Extract name
look up socket by name
    if no socket by that name, fail.
send to socket
    if socket unresponsive, fail.

**Comment by jyleong** [comment]
Kevin is building the logic right now.
Soon we will create the database model, the interaction and text processing using his logic/framework for a full end to end behaviour.

For this we will need a user model with uuid, for the on open socket method, it would look up the users model and know who to send to.

**Comment by kevinzhangftw** [comment]
look at new logic
