### ISSUE TITLE
handle conversing state

### ISSUE THREAD

**Issue by kevinzhangftw** [jyleong/voiceminder-server#33]

**Comment by kevinzhangftw** [comment]
conversing state Time out
conversing state Test
conversing state Refactor

**Comment by jyleong** [comment]
conversing state will have a class for itself
this class will use the countdown thread code
when a conversing user speaks, it will restart the countdown for their conversation

so for the two people, they only share one countdown thread

**Comment by kevinzhangftw** [comment]
see jamesdev
