### ISSUE TITLE
For Countdown class, have way to terminate/exit the single thread

### ISSUE THREAD

**Issue by jyleong** [jyleong/voiceminder-server#38]
Do this instead of closing all threads that are non main

Or use processes and know how to close specific process

**Comment by kevinzhangftw** [comment]
processes i assume work only multi core machines? also processes dont have timer functionality. maybe we can flag each thread and check the flag before closing. it would a good idea to generate a failed test case first so we can know how mark the threads before closing them.

**Comment by jyleong** [comment]
task is finished and merged into dev branch
