### ISSUE TITLE
Refactor, make websocket.py less heavy

### ISSUE THREAD

**Issue by jyleong** [jyleong/voiceminder-server#48]
websocket.py is getting dense
are there ways we can decouple some of its code

**Comment by jmloewen** [comment]
I'll look into this one to help me understand the code a bit better.

**Comment by jmloewen** [comment]
I feel like if we want to make this file smaller, it requires offloading some of the functionality of the WebSocket elsewhere.  It's already fairly slim.  Made a few changes, merge requesting this.

**Comment by kevinzhangftw** [comment]
@jmloewen you can refactor out statehandling functions into a new class called StateHandler.py
